swagger: "2.0"
info:
  title: EstateElite
  description: API for ALX Portfolio Project (EstateElite)
  version: 1.0.0
  contact:
    name: PaschalPM
    url: https://github.com/PaschalPM
    email: okaforpaschal018@gmail.com
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
definitions:
  BaseUserModel:
    description: Base User Model
    type: object
    properties:
      username:
        type: string
      email:
        type: string
        format: email
      password:
        type: string
        minLength: 8
  RequestUserCreationModel:
    allOf:
      - description: User Request Object for user registration operation
      - $ref: '#/definitions/BaseUserModel'
      - example:
          username: pasmac
          email: pasmac@gmail.com
          password: abcd1234
          confirm_password: abcd1234
      - required: [username, email, password, confirm_password]
  RequestUserLoginModel:
    allOf:
      - description: Please provide either the 'username' or 'email' property.
      - $ref: '#/definitions/BaseUserModel'
      - example:
          username: pasmac
          password: abcd1234
      - required: [password]
  ResponsePropertyModel:
    description: Get Property Object
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      category:
        type: string
        enum:
          - Commercial Property for Rent
          - Commercial Property for Sale
          - Houses & Apartments for Rent
          - Houses & Apartments for Sale
          - Land & Plots for Rent
          - Land & Plots for Sale
      address:
        type: string
      city:
        type: string
      state:
        type: string
      description:
        type: string
      price:
        type: string
      is_featured:
        type: boolean
      created_at:
        type: string
      image_urls:
        type: array
        items:
          type: string
    required:
      - id
      - title
      - category
      - address
      - city
      - state
      - desription
      - price
      - is_featured
      - created_at
      - image_urls
    example:
      id: 4a6820e1-14c2-4c34-9c55-9a9a29edbe34
      title: A gorgeous 2 bedroom apartment for sale
      category: Houses & Apartments for Sale
      address: 24 Adeola Odeku Street, Victoria Island, Lagos
      city: Lagos
      state: Lagos
      description: This 2-bedroom apartment for sale is an exquisite and visually appealing living space. With its stunning design and meticulous attention to detail, this property radiates beauty and elegance. The apartment offers a perfect blend of comfort and style, providing a luxurious and inviting atmosphere. It features two well-appointed bedrooms, ensuring ample space for relaxation and privacy. Whether you're seeking a new home or an investment opportunity, this gorgeous 2-bedroom apartment promises to captivate with its charm and allure
      price: ₦70,000,000.00
      is_featured: true
      created_at: 1 hour ago
      image_urls:
        - /static/images/image-1.jpg
        - /static/images/image-2.jpg
        - /static/images/image-3.jpg
        - /static/images/image-4.jpg
  ResponsePropertiesModel:
    type: array
    items:
      allOf:
        - $ref: '#/definitions/ResponsePropertyModel'
  NewPropertyModel:
    description: Post Property Object
    type: object
    properties:
      title:
        type: string
      category:
        type: string
        enum:
          - Commercial Property for Rent
          - Commercial Property for Sale
          - Houses & Apartments for Rent
          - Houses & Apartments for Sale
          - Land & Plots for Rent
          - Land & Plots for Sale
      address:
        type: string
      city:
        type: string
      state:
        type: string
      description:
        type: string
      price:
        type: integer
      images:
        type: array
        items:
          type: string
        minItems: 3
        maxItems: 5
    required:
      - title
      - category
      - address
      - city
      - state
      - description
      - price
      - images
    example:
      title: A gorgeous 2 bedroom apartment for sale
      category: Houses & Apartments for Sale
      address: 24 Adeola Odeku Street, Victoria Island, Lagos
      city: Lagos
      state: Lagos
      description: This 2-bedroom apartment for sale is an exquisite and visually appealing living space. With its stunning design and meticulous attention to detail, this property radiates beauty and elegance. The apartment offers a perfect blend of comfort and style, providing a luxurious and inviting atmosphere. It features two well-appointed bedrooms, ensuring ample space for relaxation and privacy. Whether you're seeking a new home or an investment opportunity, this gorgeous 2-bedroom apartment promises to captivate with its charm and allure
      price: 70000000
      images:
        - "data:image/jpeg;base64,iVBORw0KG... (the rest of your Data URL)"
        - "data:image/png;base64,jkgserth... (the rest of your Data URL)"
        - "data:image/jpeg;base64,i06jgdf... (the rest of your Data URL)"
     
paths:
  /auth/register:
    post:
      summary: Create new user
      description: Create new user
      parameters:
        - name: payload
          in: body
          required: true
          schema:
            $ref: '#/definitions/RequestUserCreationModel'
      responses:
        201:
          description: User created successfully
        400:
          description: Bad Request
          schema:
            type: object
            example:
              error:
                code: 400
                description: Invalid user request
                message: The request body is missing required fields or contains invalid data
        409:
          description: Conflict
          schema:
            type: object
            example:
              error:
                code: 409
                description: Conflict
                message: Username already exists
 
  /auth/login:
    post:
      summary: Login user and get JWT access token
      description:  "NOTE: Please provide either the 'username' or 'email' property."
      parameters:
        - name: payload
          in: body
          required: true
          schema:
            $ref: '#/definitions/RequestUserLoginModel'
      responses:
        200:
          description: User logged in
          schema:
            type: object
            example:
              access_token: 4a6820e1-14c2-4c34-9c55-9a9a29edbe34
        401:
          description: Unauthorized
          schema:
            type: object
            example:
              error:
                code: 401
                description: Invalid credentials
                message: The provided username and password combination is incorrect
 
  /auth/refresh:
    post:
      summary: Refresh token
      description: Refresh access tokens from refresh tokens sent as cookie
      parameters:
        - name: refresh_token
          description: refresh_token should be sent as a cookie
          in: header
          required: true
          type: string
      responses:
        200:
          description: User logged in
          schema:
            type: object
            example:
              access_token: 4a6820e1-14c2-4c34-9c55-9a9a29edbe34
        401:
          description: Unauthorized
          schema:
            type: object
            example:
              error:
                code: 401
                description: Unauthorized
                message: Invalid or expired refresh token
        403:
          description: Forbidden
          schema:
            type: object
            example:
              error:
                code: 403
                description: Forbidden
                message: Insufficient permissions to obtain an access token (blacklisted)
 
  /auth/logout:
    delete:
      summary: logout users
      description: logout user and revoke jwt tokens
      responses:
        200:
          description: User logged out
         
  /properties:
    get:
      summary: Get all properties
      description: Get all properties with image urls
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/ResponsePropertiesModel'
  
  /properties/categories:
    get:
      summary: Get all property categories
      description: Get all property categories
      responses:
        200:
          description: Ok
          schema:
            example:
              data:
                - Commercial Property for Rent
                - Commercial Property for Sale
                - Houses & Apartments for Rent
                - Houses & Apartments for Sale
                - Land & Plots for Rent
                - Land & Plots for Sale
  /properties/{ppty_id}:
    get:
      summary: Get single property
      description: Get single property with image urls
      parameters:
        - in: path
          name: ppty_id
          description: This is the property's uuid to retrieve a single property record
          required: true
          type: string
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/ResponsePropertyModel'
 
  /users/{user_id}/properties:
    get:
      summary: Get all properties of a User
      description: Get all properties of a User with image urls
      parameters:
        - in: path
          name: user_id
          required: true
          type: string
          description: this is the user's uuid to retrieve properties created by him
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ResponsePropertiesModel'
    post:
      summary: Add new property
      description: Adds a new property with compressed images
      parameters:
        - in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/NewPropertyModel'
        - in: path
          name: user_id
          required: true
          type: string
          description: this is the user's uuid to post a new property
         
      responses:
        201:
          description: "Returns the uuid of the new property created"
          schema:
            $ref: '#/definitions/ResponsePropertyModel'
           
 
  /users/{user_id}/properties/{ppty_id}:
    get:
      summary: Get a single property
      description: Get single property with image urls
      parameters:
        - in: path
          name: user_id
          description: This is the user's uuid to access his property records
          required: true
          type: string
        - in: path
          name: ppty_id
          description: This is the property's uuid to retrieve a single property record
          required: true
          type: string
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/ResponsePropertyModel'
    delete:
      summary: Delete a single property
      description: Delete a single property with all its images
      parameters:
        - in: path
          name: user_id
          description: This is the user's uuid to access his property records
          required: true
          type: string
        - in: path
          name: ppty_id
          description: This is the property's uuid to delete a single property record
          required: true
          type: string
      responses:
        204:
          description: No Content